import Head from 'next/head'
import styles from '../styles/Home.module.css'

import Header from '../components/header'

import UploadPage from './uploadPage'
import AllocationPage from './allocationPage'

import { Text, Link } from "@nextui-org/react";
import YellowButton from '../components/yellowButton'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>MMM</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>

      <div className={styles.container}>

        <main className={styles.main}>
        <div className={styles.windowConfirmation}>
            
            <div style={{padding: '2rem', textAlign: "center"}}>
                <Text h2 style={{marginTop: '2rem', marginBottom: '2rem'}}>Welcome to the CBA Mentor Mentee Matcher Tool</Text>
                <Text>The tool that allows users to easily manage, modify and export mentor-mentee matches.</Text>
                <Text style={{paddingTop: '1rem'}}>Ready to get started?</Text>
            </div>
    
            <div className={styles.buttonContainer} style={{display: 'inline-flex', justifyContent: 'center', marginTop: '2rem', paddingLeft: '2rem', paddingRight: '2rem'}}>
              <Link href="uploadPage" style={{color:'black' }}><YellowButton>Next</YellowButton></Link>
            </div>
            
        </div>
        </main>


    </div>
    </div>
  )
}
